# Generated by Django 4.0 on 2022-01-31 15:10

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200, verbose_name='имя проекта')),
                ('project_description', tinymce.models.HTMLField(verbose_name='описание проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='images/users', verbose_name='Изображение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_theme', models.CharField(max_length=200, verbose_name='тема задания')),
                ('task_description', models.TextField(verbose_name='описание задания')),
                ('task_datestart', models.DateTimeField(verbose_name='начало задания')),
                ('task_dateend', models.DateTimeField(verbose_name='окончания задания')),
                ('task_type', models.CharField(choices=[('Фича', 'Фича'), ('Баг', 'Баг')], max_length=30, verbose_name='тип задания')),
                ('task_priority', models.CharField(choices=[('Нормальный', 'Нормальный'), ('Высокий', 'Высокий'), ('Срочный', 'Срочный')], max_length=30, verbose_name='приоритет задания')),
                ('task_spenttime', models.IntegerField(verbose_name='время на задание(в часах)')),
                ('task_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_author', to='auth.user', verbose_name='автор')),
                ('task_executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executor', to='auth.user', verbose_name='исполнитель')),
                ('task_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_description', models.TextField(max_length=200, verbose_name='комментарий')),
                ('comment_date', models.DateTimeField(verbose_name='дата комментария')),
                ('coment_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.task', verbose_name='коментарий к задаче')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='auth.user', verbose_name='автор комментария')),
            ],
        ),
    ]
