# Generated by Django 4.0 on 2022-01-31 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0002_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_description', models.TextField(max_length=200, verbose_name='комментарий')),
                ('comment_date', models.DateTimeField(verbose_name='дата комментария')),
                ('coment_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.task', verbose_name='коментарий к задаче')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='auth.user', verbose_name='автор комментария')),
            ],
        ),
    ]
