# Generated by Django 4.0 on 2022-01-31 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_newcomment_comment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newcomment',
            old_name='coment_task',
            new_name='comment_task',
        ),
    ]
