# Generated by Django 4.0 on 2022-01-31 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_coment_task_newcomment_comment_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcomment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
