# Generated by Django 4.0 on 2022-02-01 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0006_alter_newcomment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='команда'),
        ),
        migrations.AlterField(
            model_name='newcomment',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='auth.user', verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='newcomment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='newcomment',
            name='comment_description',
            field=models.TextField(max_length=200, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='newcomment',
            name='comment_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.task', verbose_name='Имя  задачи №'),
        ),
    ]
